# create_ec2.yml
---
- hosts: localhost  
  gather_facts: no
  vars:
    ami_id: "ami-09d95fab7fff3776c"
    role: "image-gallery-role"
  module_defaults: 
    group/aws: 
      region: "us-east-1"
  tasks:
    - name: Provision EC2 Instance
      ec2:
        key_name: module-5-key
        group: Module5-default
        instance_type: t3.nano
        image: "{{ ami_id }}"
        instance_tags:
          Name: m5-development
          Module: 5
        monitoring: yes
        wait: yes
        vpc_subnet_id: "{{ public1_subnet.subnet.id }}"
        exact_count: 1
        count_tag:
          Name: m5-development
        assign_public_ip: yes
        instance_profile_name: "{{ role }}"