# hosts
---
plugin: aws_ec2

regions:
  - us-east-1
keyed_groups:
  - key: tags.Name
    prefix: tag_Name_
    separator: ""
  - key: tags.Module
    prefix: tag_Module_
    separator: ""

# all:
#   hosts:
#     ec2-3-223-191-14.compute-1.amazonaws.com:
#       ansible_user: ec2-user
#       ansible_python_interpreter: /usr/bin/python
#     ec2-18-206-135-40.compute-1.amazonaws.com:
#       ansible_user: ec2-user
#       ansible_python_interpreter: /usr/bin/python
#     ec2-34-233-71-4.compute-1.amazonaws.com:
#       ansible_user: ubuntu
#   children:
#     amazonlinux2:
#       hosts:
#         ec2-3-223-191-14.compute-1.amazonaws.com:
#         ec2-18-206-135-40.compute-1.amazonaws.com:
#     ubuntu:
#       hosts:
#         ec2-34-233-71-4.compute-1.amazonaws.com:

